### PR TITLE
Implemented AcmeCache trait

### LINKED ISSUE #3: Switch cache directory with a trait to allow other storage backends
First off, thank you so much for this crate and for the quick merges on the pull requests I sent in last night.

I'm building a database which has its own encrypted-at-rest storage available, and I would like to be able to act as the account cache myself. I can manually manage the account and certificates if I drive the process by hand, but I can't use the `rustls_helper::order` function because that function returns a `CertifiedKey` which cannot be used to export the private key.

I propose changing the order function to take a trait implementation rather than a Path for the cache, with function calls to load and save accounts and certificates with their keys. The crate can continue to provide a filesystem implementation.

Would you be open to a pull request for this change?

### PR DESCRIPTION
**Pull request by ecton**
Fixes #3.

This uses async_trait to expose an interface to implement custom cache backends. An implementation for the filesystem is still provided.

Existing code should work -- in the hyper_rustls example, filling in the cache_dir setting compiles properly. The changes in the example file are primarily updates to support rustls 0.20.

I tried to make a blanket implementation for `AsRef<Path>` work, but I couldn't get Rust to infer the types on the actual order invocation -- it kept asking me to manually specify the type parameters. By using the macro approach, it allows existing code that uses Path/PathBuf and String/str to continue working.

I did notice on the async-std example that this breaks, because async-std provides its own PathBuf type. I was in the process of trying to just change the example to use std::path::PathBuf, but then discovered #4.

Please let me know if you have any feedback!

### CODE REVIEW

**Comment by ecton** [comment]
I hooked this new code up [into my database](https://github.com/khonsulabs/bonsaidb/blob/46cca5ebe4f24770ef52a651dbc0effe946537e1/crates/bonsaidb-server/src/server/acme.rs#L78-L135), and it works properly, but it was a breaking change. I'm not sure if I can address it or not. If you pass in an `Option<PathBuf>` instead of a reference, it doesn't work because it currently requires a reference instead of an AsRef.

When I try to introduce the AsRef, it causes the order invocation to require types to be specified again. The code fix is simple, just as_ref() it before passing it in.

If you have any ideas on how to make this not a breaking change, I'm happy to try other ideas.

**Comment by User65k** [comment]
I would suggest:
- moving `AcmeCache` to `fs`
- moving `Account::cached_key_file_name` to `fs`
- deleting `fs::read_if_exist` and `fs::write_file` in order to directly put it into the trait
- renaming `fs` to `cache`
- and finally the impl like this:
```rust
#[async_trait]
impl<P> AcmeCache for P where P: AsRef<Path>+Send+Sync {
    type Error = std::io::Error;

    async fn read_account(
        &self,
        contacts: &[&str],
    ) -> Result<Option<Vec<u8>>, Self::Error> {
        let file = cached_key_file_name(contacts);
        let mut path = self.as_ref().to_path_buf();
        path.push(file);
        match read(path).await {
            Ok(content) => Ok(Some(content)),
            Err(err) => match err.kind() {
                ErrorKind::NotFound => Ok(None),
                _ => Err(err),
            },
        }
    }

    async fn write_account(
        &self,
        contacts: &[&str],
        contents: &[u8],
    ) -> Result<(), Self::Error> {
        let mut path = self.as_ref().to_path_buf();
        create_dir_all(&path).await?;
        path.push(cached_key_file_name(contacts));
        Ok(write(path, contents).await?)
    }

    async fn write_certificate(
        &self,
        domains: &[String],
        directory_url: &str,
        key_pem: &str,
        certificate_pem: &str,
    ) -> Result<(), Self::Error> {
        let hash = {
            let mut ctx = sha256_hasher();
            for domain in domains {
                ctx.update(domain.as_ref());
                ctx.update(&[0])
            }
            // cache is specific to a particular ACME API URL
            ctx.update(directory_url.as_bytes());
            base64::encode_config(ctx.finish(), base64::URL_SAFE_NO_PAD)
        };
        let file = AsRef::<Path>::as_ref(self).join(&format!("cached_cert_{}", hash));
        let content = format!("{}\n{}", key_pem, certificate_pem);
        write(&file, &content).await?;
        Ok(())
    }
}
```

It compiles and the fs stuff was not public and just a helper for the default caching. What do you think?

**Comment by ecton** [comment]
Thank you for the feedback. Good catch on the macro implementations not actually being needed anymore -- they were part of my failed attempt to allow `impl AsRef<impl AcmeCache>` as the parameter rather than `&impl AcmeCache`.

I went ahead and did one other thing -- I tend to dislike modules that only have one item inside of them. I originally was writing a comment suggesting `pub use cache::AcmeCache` at the top-level, but I renamed `AnyError` to `CacheError` and moved it into `cache`. This makes the module contain two items, which seems more reasonable to leave as a `pub mod`.

What do you think of these changes? Can you think of anything I missed?

**Comment by User65k** [comment]
Looks good to me.
Just one more thing: Could you add some docstrings to AcmeCache?

**Comment by ecton** [comment]
I've added some documentation, and I also rebased this branch so that I could verify generating docs works with both `async_std_rustls` and `hyper_rustls`.

The docs for async_traits aren't good, but I still prefer using async_traits to requiring users to deal with alternatives.

**Pull request merged**
